# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_auto_20170913_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='invent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='invent',
            name='name',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='outvent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='rbustatus',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='status',
            name='time',
            field=models.TimeField(verbose_name='время'),
        ),
    ]
