# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statuses', '0003_auto_20170914_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='status',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='datetime',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='дата'),
        ),
    ]
