# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 00:02
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statuses', '0004_auto_20180208_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-datetime'], 'verbose_name': 'статус РБУ', 'verbose_name_plural': 'статусы РБУ'},
        ),
        migrations.AlterField(
            model_name='status',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='дата'),
            preserve_default=False,
        ),
    ]
