# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 18:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('statuses', '0005_auto_20180328_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='unload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='unloads.Unload', verbose_name='Выгрузка'),
        ),
    ]
