# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unloads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unload',
            name='date',
            field=models.DateField(verbose_name='дата'),
        ),
    ]
