# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 18:40
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('unloads', '0002_auto_20170910_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unload',
            options={'ordering': ['datetime'], 'verbose_name': 'отгрузка', 'verbose_name_plural': 'отгрузки'},
        ),
        migrations.RemoveField(
            model_name='unload',
            name='date',
        ),
        migrations.AddField(
            model_name='unload',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unload',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unload',
            name='datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='дата'),
            preserve_default=False,
        ),
    ]
