# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='дата')),
                ('value', models.IntegerField(default=0, verbose_name='количество цемента')),
            ],
        ),
    ]
