# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cement',
            options={'ordering': ['-date'], 'verbose_name': 'Отчет по цементу',
                     'verbose_name_plural': 'Отчеты по цементу'},
        ),
    ]
