# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата')),
                ('value', models.FloatField(default=1, verbose_name='объем')),
                ('him', models.FloatField(default=0, verbose_name='химия')),
                ('water', models.FloatField(default=0, verbose_name='вода')),
                ('cement', models.FloatField(default=0, verbose_name='цемент')),
                ('breakstone', models.SmallIntegerField(default=0, verbose_name='щебень')),
                ('sand', models.SmallIntegerField(default=0, verbose_name='песок')),
            ],
            options={
                'verbose_name': 'Машина',
                'ordering': ['date'],
                'verbose_name_plural': 'машины',
            },
        ),
        migrations.CreateModel(
            name='Unload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата')),
                ('value', models.FloatField(default=None, null=True, verbose_name='объем')),
                ('him', models.FloatField(default=0, verbose_name='химия')),
                ('water', models.FloatField(default=0, verbose_name='вода')),
                ('cement', models.FloatField(default=0, verbose_name='цемент')),
                ('breakstone', models.SmallIntegerField(default=0, verbose_name='щебень')),
                ('sand', models.SmallIntegerField(default=0, verbose_name='песок')),
                ('is_active_left_bunker', models.NullBooleanField(verbose_name='активный бункер - левый')),
                ('carrier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unload.Carrier', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'отгрузка',
                'ordering': ['date'],
                'verbose_name_plural': 'отгрузки',
            },
        ),
        migrations.CreateModel(
            name='UnloadType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый тип отгрузки', max_length=127, verbose_name='имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('him', models.FloatField(default=0, verbose_name='химия')),
                ('water', models.FloatField(default=0, verbose_name='вода')),
                ('cement', models.FloatField(default=0, verbose_name='цемент')),
                ('breakstone', models.PositiveSmallIntegerField(default=0, verbose_name='щебень')),
                ('sand', models.PositiveSmallIntegerField(default=0, verbose_name='песок')),
                ('average_him', models.FloatField(default=0, verbose_name='химия в среднем')),
                ('average_water', models.FloatField(default=0, verbose_name='вода в среднем')),
                ('average_cement', models.FloatField(default=0, verbose_name='цемент в среднем')),
                ('average_breakstone', models.PositiveSmallIntegerField(default=0, verbose_name='щебень в среднем')),
                ('average_sand', models.PositiveSmallIntegerField(default=0, verbose_name='песок в среднем')),
            ],
            options={
                'verbose_name': 'тип отгрузки',
                'verbose_name_plural': 'типы отгрузок',
            },
        ),
        migrations.AddField(
            model_name='unload',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unload.UnloadType', verbose_name='тип'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unload.UnloadType', verbose_name='тип'),
        ),
    ]
