# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата')),
                ('value', models.FloatField(default=1, verbose_name='объем')),
                ('him', models.FloatField(default=0, verbose_name='химия')),
                ('water', models.FloatField(default=0, verbose_name='вода')),
                ('cement', models.FloatField(default=0, verbose_name='цемент')),
                ('breakstone', models.SmallIntegerField(default=0, verbose_name='щебень')),
                ('sand', models.SmallIntegerField(default=0, verbose_name='песок')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unload.UnloadType', verbose_name='тип')),
            ],
            options={
                'verbose_name': 'Машина',
                'ordering': ['date'],
                'verbose_name_plural': 'машины',
            },
        ),
        migrations.AddField(
            model_name='unload',
            name='carrier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unload.Carrier', verbose_name='Машина'),
        ),
    ]
